name: Electron Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Set GitHub token as an environment variable
      - name: Set up environment variables
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      # Enable i386 architecture and install Wine and Mono
      - name: Install Wine and Mono
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine wine32 mono-complete

      - name: Build for Linux
        run: npx electron-builder -l AppImage -w

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: launcher-linux-artifact
          path: dist/*.AppImage

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/*.zip
